export default [
  { name: '~', span: 2 },
  { name: '1', span: 2 },
  { name: '2', span: 2 },
  { name: '3', span: 2 },
  { name: '4', span: 2 },
  { name: '5', span: 2 },
  { name: '6', span: 2 },
  { name: '7', span: 2 },
  { name: '8', span: 2 },
  { name: '9', span: 2 },
  { name: '0', span: 2 },
  { name: '-', span: 2 },
  { name: '=', span: 2 },
  { name: 'back', span: 4 },

  { name: 'tab', span: 3 },
  { name: 'Q', span: 2 },
  { name: 'W', span: 2 },
  { name: 'E', span: 2 },
  { name: 'R', span: 2 },
  { name: 'T', span: 2 },
  { name: 'Y', span: 2 },
  { name: 'U', span: 2 },
  { name: 'I', span: 2 },
  { name: 'O', span: 2 },
  { name: 'P', span: 2 },
  { name: '[', span: 2 },
  { name: ']', span: 2 },
  { name: '|', span: 3 },

  { name: 'Caps', span: 4 },
  { name: 'A', span: 2 },
  { name: 'S', span: 2 },
  { name: 'D', span: 2 },
  { name: 'F', span: 2 },
  { name: 'G', span: 2 },
  { name: 'H', span: 2 },
  { name: 'J', span: 2 },
  { name: 'K', span: 2 },
  { name: 'L', span: 2 },
  { name: '', span: 2 },
  { name: '&quot', span: 2 },
  { name: 'enter', span: 4 },

  { name: 'shift', span: 5 },
  { name: 'Z', span: 2 },
  { name: 'X', span: 2 },
  { name: 'C', span: 2 },
  { name: 'V', span: 2 },
  { name: 'B', span: 2 },
  { name: 'N', span: 2 },
  { name: 'M', span: 2 },
  { name: ',', span: 2 },
  { name: '.', span: 2 },
  { name: '/', span: 2 },
  { name: 'shift', span: 5 },

  { name: 'ctl', span: 4 },
  { name: 'start', span: 2 },
  { name: 'alt', span: 2 },
  { name: 'space', span: 16 },
  { name: 'alt', span: 2 },
  { name: 'ctl', span: 4 }

]
